- type: job
  id: Chaplain
  name: job-name-cleric # Stellar - Chaplains to Clerics
  description: job-description-chaplain
  playTimeTracker: JobChaplain
  startingGear: ChaplainGear
  icon: "JobIconChaplain"
  supervisors: job-supervisors-hop
  access:
  - Chapel
  - Maintenance
  # special: # Stellar Begin - Chaplains to Clerics
  # - !type:AddComponentSpecial
  #   components:
  #   - type: BibleUser #Lets them heal with bibles # Stellar End - Chaplains to Clerics

- type: startingGear
  id: ChaplainGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: ChaplainPDA
    ears: ClothingHeadsetService
  storage:
    back:
    # - Bible # Stellar - Chaplains to Clerics
    - PrayerBook # Stellar - Chaplains to Clerics
    - RubberStampChaplain

- type: chameleonOutfit
  id: ChaplainChameleonOutfit
  job: Chaplain
  equipment:
    head: ClothingHeadHatPlaguedoctor
    eyes: ClothingEyesGlasses
    mask: ClothingMaskPlague
    neck: ClothingNeckStoleChaplain
    outerClothing: ClothingOuterPlagueSuit
    gloves: ClothingHandsGlovesColorBlack

